### PR TITLE
Submission for Gitcoin Bounty (WIP)

### PR DESCRIPTION
**Pull request by olafghanizadeh**
Given the desired submission deadline I am opening a PR for my work so far. There are some things left to do and a bit of polishing, but I hope you appreciate the work that has been done so far.

Images used is from Shutterstock and the design uses bits from Shards UI (https://github.com/DesignRevision/shards-ui)

localhost_8000_ 1

### CODE REVIEW

**Comment by TimVanMourik** [comment]
Necessary changes before merge:

Welcome page: 
* [x] 'take for a spin' links to non-existing 'our-services, probably from a template. Let's link it to (perhaps a random) example?
* [x] 'card image cap' for each example to be removed or replaced
* [x] Add instructions as mentioned on Slack
* [x] @dokato, @dcmoyer, change personal description
* [ ] If you want a small 'design by <a> @olafghanizadeh </a>' in the bottom corner, go right ahead :) 

AR page:
* [x] Make pop-up panel closable
  * [x] Let's not bother about automation here. Just a good ol' close button :)
* [x] Make all clickable things responsive again
* [x] Centre the marker. horizontally shrink the pop-up

**Comment by dokato** [comment]
Wow, I really like it. However there are still things to consider:

**AR page:**
In the current state is not usable. I'd reverse the changes of the sidebar (just leave the background white) and change a border to the blue one (matching welcome page).
screen shot 2018-07-16 at 13 42 01

**Welcome page:**
* [ ] I think that authors cards could be in columns similarly to examples.
* [x] Examples should have "open example" message rather than "read more"
* [ ] I'd make a top blue header smaller such that examples buttons are visible straight away even on smaller screens.
* [x] Armadillo -> ARmadillo

But don't be mislead by the number of corrections, overall I'm really satisfied with the submission 👍

**Comment by dokato** [comment]
@TimVanMourik @olafghanizadeh who is working on this? Cause I see tick-offs but no commits with them.

**Comment by TimVanMourik** [comment]
I started ticking of buttons in branch `pr/21`. Have a look! :)

**Comment by TimVanMourik** [comment]
Merged via separate branch `pr/21`

**Comment by TimVanMourik** [comment]
Merged via separate branch `pr/21`

**Comment by dokato** [comment]
I see, cool :)

**Pull request merged**
