### PR TITLE
Custom marker 

### PR DESCRIPTION
**Pull request by TimVanMourik**
Solution to #4.

@dokato made this work with a custom marker! 😄  I made some small changes to fix colouring problems and small stylistic updates to the marker. 

Could you please review this @dokato @dcmoyer?

### CODE REVIEW

**Comment by dokato** [comment]
LGTM :)

**Comment by TimVanMourik** [comment]
I quickly added an <a> tag around the image to make it clickable, thereby solving issue #8

**Comment by dokato** [comment]
@TimVanMourik regarding your last change: most solution from ARjs suggest actually using absolute path for markers rather than relative ones. Maybe that causes the problem?

**Comment by dokato** [comment]
If not I suggest reverting to the last commint and agreeing with the last working brain marker ;)

**Comment by TimVanMourik** [comment]
I tried both, it really looks like the marker itself happens to be bad for tracking. No idea why. So let's indeed revert for now and I'll try and find the problem in the meantime.

**Comment by dokato** [comment]
@TimVanMourik should we merge #14 for now and close this one? At least we have one solution with brain marker. We can adjust the brain size/shape later on. WDYT?

**Comment by TimVanMourik** [comment]
Agreed @dokato, closing this issue. Let's update the marker later on if desired.

**Pull request closed without merging**
